return function(colors)
	return {
		CmpItemAbbr = { fg = C.overlay2 },
		CmpItemAbbrDeprecated = { fg = colors.red, strikethrough = true },
		CmpItemKind = { fg = colors.jordyblue },
		CmpItemMenu = { fg = colors.overlay0 },
		CmpItemAbbrMatch = { fg = colors.red, bold = colors.bold },
		CmpItemAbbrMatchFuzzy = { fg = colors.red , bold = colors.bold },

		CmpItemKindSnippet = { fg = colors.pink3 },
		CmpItemKindKeyword = { fg = colors.red },
		CmpItemKindText = { fg = colors.skyblue },
		CmpItemKindMethod = { fg = colors.jordyblue },
		CmpItemKindConstructor = { link = "CmpItemKindMethod" },
		CmpItemKindFunction = { link = "CmpItemKindMethod" },
		CmpItemKindFolder = { link = "CmpItemKindMethod" },
		CmpItemKindModule = { link = "CmpItemKindMethod" },
		CmpItemKindConstant = { fg = colors.peach },
		CmpItemKindField = { fg = colors.powderblue },
		CmpItemKindProperty = { fg = colors.lightgreen },
		CmpItemKindEnum = { link = "CmpItemKindProperty" },
		CmpItemKindUnit = { link = "CmpItemKindProperty" },
		CmpItemKindClass = { fg = colors.yellow },
		CmpItemKindVariable = { fg = colors.skyblue },
		CmpItemKindFile = { link = "CmpItemKindMethod" },
		CmpItemKindInterface = { link = "CmpItemKindClass" },
		CmpItemKindColor = { fg = colors.red },
		CmpItemKindReference = { link = "CmpItemKindColor" },
		CmpItemKindEnumMember = { link = "CmpItemKindColor" },
		CmpItemKindStruct = { link = "CmpItemKindMethod" },
		CmpItemKindValue = { fg = colors.peach },
		CmpItemKindEvent = { link = "CmpItemKindMethod" },
		CmpItemKindOperator = { link = "CmpItemKindMethod" },
		CmpItemKindTypeParameter = { link = "CmpItemKindMethod" },
		CmpItemKindCopilot = { fg = colors.lighgreen },

	}
end
