return function(self)
	return {
		["@comment"] = { link = "Comment" },
		["@error"] = { link = "Error" },
		["@preproc"] = { link = "PreProc" },
		["@conditional"] = { link = "Keyword" },
		["@repeat"] = { link = "Keyword" },
		["@define"] = { link = "Define" },
		["@include"] = { link = "Include" },
		["@operator"] = { link = "Operator" },
		["@namespace"] = { link = "Type" },
		["@type"] = { link = "Type" },
		["@type.definition"] = { link = "Type" },
		["@type.builtin"] = { link = "Type" },
		["@variable"] = { fg = self.foreground[1] },
		["@field"] = { fg = self.extra.periwinkle[3] },
		["@property"] = { fg = self.extra.periwinkle[3] },
		["@parameter"] = { fg = self.extra.periwinkle[1] },
		["@function"] = { fg = self.blue[1] },
		["@function.builtin"] = { link = "Function" },
		["@function.call"] = { fg = self.blue[1] },
		["@punctuation.bracket"] = { fg = self.foreground[3] },
		["@punctuation.delimiter"] = { fg = self.foreground[3] },
		["@constructor.lua"] = { fg = self.foreground[3] },

		["@lsp.type.parameter"] = { link = "@parameter" },
		["@lsp.type.type"] = { link = "@type" },
		["@lsp.type.struct"] = { link = "@type" },
	}
end
