return function(colors)
	return {
		Normal = { bg = colors.bg, fg = colors.overlay0 },
		NormalNC = { link = "Normal" },
		NormalSB = { link = "Normal" },
		ColorColumn = { bg = colors.surface1 },
		Conceal = { fg = colors.overlay5 },
		Cursor = { fg = colors.bg, bg = colors.overlay0 },
		lCursor = { link = "Cursor" },
		CursorIM = { link = "Cursor" },
		CursorColumn = { bg = colors.surface1 },
		CursorLine = { link = "CursorColumn" },
		Directory = { fg = colors.skyblue },
		ErrorMsg = { fg = colors.red, italic = colors.italic, bold = colors.bold },
		WarningMsg = { fg = colors.peach },
		VertSplit = { fg = colors.surface1 },
		Folded = { fg = colors.jordyblue, bg = colors.surface1 },
		FoldColumn = { bg = colors.bg },
		LineNr = { fg = colors.overlay5 },
		CursorLinenr = { fg = colors.overlay0, bg = colors.surface1 },
		MatchParen = { bold = colors.bold, fg = colors.peach },
		ModeMsg = { fg = colors.overlay0, bold = colors.bold },
		MsgSeparator = {},
		MoreMsg = { fg = colors.jordyblue },
		NonText = { fg = colors.overlay2 },
		NormalFloat = { bg = colors.surface2 },
		FloatBorder = { fg = colors.surface4 },
		TabLine = { bg = colors.surface2 },
		Pmenu = { bg = colors.bg, fg = colors.overlay2 },
		PmenuSel = { bold = colors.bold },
		PmenuSbar = { bg = colors.surface1 },
		PmenuThumb = { bg = colors.overlay4 },
		Question = { bg = colors.jordyblue },
		QuickFixLine = { bg = colors.surface1, bold = colors.bold },
		Visual = { bg = colors.surface1, bold = colors.bold },
		StatusLine = { bg = colors.surface2 }
	}
end
