return function(colors)
	return {
		Comment = { fg = colors.overlay4 },
		SpecialComment = { link = "Special" },
		Constant = { fg = colors.melon },
		String = { fg = colors.lightgreen },
		Character = { fg = colors.periwinkle },
		Number = { fg = colors.peach },
		Float = { link = "Number" },
		Boolean = { link = "Number" },
		Identifier = { fg = colors.overlay0 },
		Function = { fg = colors.jordyblue },
		Statement = { fg = colors.pink3 },
		Conditional = { link = "Statement" },
		Repeat = { fg = colors.skyblue },
		Label = { link = "Repeat" },
		Operator = { fg = colors.red },
		Error = { fg = colors.red, bold = colors.bold },
		Keyword = { fg = colors.red },
		PreProc = { fg = colors.melon },
		Include = { link = "PreProc" },
		Define = { link = "PreProc" },
		Macro = { link = "PreProc" },
		PreCondit = { link = "PreProc" },
		StorageClass = { fg = colors.powderblue },
		Structure = { link = "Keyword" },
		Special = { fg = colors.pink0 },
		Question = { fg = colors.jordyblue, bg = "NONE", bold = colors.bold },
		Type = { fg = colors.periwinkle },
		Delimiter = { fg = colors.overlay3 },
		Tag = { link = "Special" },
		Debug = { link = "Special" },
		Todo = { fg = colors.yellow },
		healthError = { fg = colors.red },
		healthSuccess = { fg = colors.lightgreen },
		healthWarning = { fg = colors.yellow },
		Bold = { bold = colors.bold },
		Italic = { italic = colors.italic }
	}
end
